### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by stuartgunter** [stuartgunter/dropwizard-cassandra#19]
I'd appreciate input on this from @manub and @mmusnjak, given that you've recently helped with PRs and other suggestions.

I'm looking at versioning and it seems more complicated than it needs to be. Initially the intention was to support multiple versions of both Dropwizard and Cassandra driver, but the reality is that we're only tracking the latest version of each. The Cassandra driver supports all Cassandra versions, so there doesn't appear to be a need to support anything other than the latest version of the driver. And Dropwizard's interface has been very stable over the last release (from 0.8.x to 0.9.x).

What do you think about changing versioning to be a simple semantic versioning scheme only for this library? In other words, changing from `1.0-dw0.9-cs2.1` to just `1.0.0` (for example)?

**Comment by manub** [comment]
I agree this is a good idea in regards of the Cassandra Driver.

Regarding Dropwizard, I'd be a bit more on the conservative side. While I haven't investigated the differences in the APIs, I had previous experience of similar problems with other Dropwizard related libraries. If they aren't significantly different, would it make sense use a `provided` scope in the build so users can bring the library in their project regardless of the version of Dropwizard they're using? (provided that the APIs for bundles aren't changed between versions) This could work as I don't think anybody is using the library without importing Dropwizard first anyway.

Or the default version could be changed to `1.0.0` as you suggest, carrying on active development only for latest Dropwizard, and having a different version for releases which are developed against Dropwizard `0.8.x` (which reflects the actual scheme, but it would be specifically for an old version of Dropwizard). This also allows maintaining only the most recent version (while contributors that could be interested could eventually backport new features appeared on the master development branch).

**Comment by stuartgunter** [comment]
Thanks for the feedback.

It seems Dropwizard has been pretty stable in terms of API changes. There was no API incompatibility from 0.8.x to 0.9.x that affected this library.

How about we wait for Dropwizard to reach the v1.0 milestone and then move to a simple semver approach for this library too? So in other words, don't change anything now - but switch over when DW reaches 1.0.

**Comment by manub** [comment]
Looks good to me.

**Comment by mmusnjak** [comment]
I agree.

**Comment by stuartgunter** [comment]
I'll close this then and make the changes with DW goes 1.0

Thanks for your input.
