### ISSUE TITLE
Upgrade cassandra driver to 2.1.4

### ISSUE THREAD

**Issue by gordysc** [stuartgunter/dropwizard-cassandra#9]
Datastax has made some significant improvements since the 2.0.3 release.  Can we upgrade this module to use the latest driver (2.1.4)?

**Comment by stuartgunter** [comment]
The project currently supports two strands of Cassandra: 2.0.x and 2.1.x.

If you want to use version 2.1.x, it might just be necessary to update your project build script to include the correct GAV from Maven Central. Full details are listed here: http://www.stuartgunter.org/changes-to-dropwizard-cassandra/

Assuming a Maven build, you could just use the following configuration in `pom.xml`:

```xml
<dependencyManagement>
  <dependency>
    <groupId>com.datastax.cassandra</groupId>
    <artifactId>cassandra-driver-core</artifactId>
    <version>2.1.4</version>
  </dependency>
</dependency>
<dependencyManagement>
<dependency>
    <groupId>org.stuartgunter</groupId>
    <artifactId>dropwizard-cassandra</artifactId>
    <version>1.0-dw0.7-cs2.1</version>
</dependency>
```

You only need the `dependencyManagement` section if you need/want to use v2.1.4 of the Cassandra driver. If you don't specify this, it'll use v2.1.2 instead.

Does that solve your problem?

**Comment by gordysc** [comment]
Ah, didn't see the other version, thanks.  And yup, was already specifying the 2.1.4 explicitly.  Great module bud, thanks for this!

**Comment by stuartgunter** [comment]
No problem. Thanks.
